version: "3.9"

services:
  atm_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=atm_credit_db
      - POSTGRES_USER=alexey
      - POSTGRES_PASSWORD=alexey
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5460:5432"

volumes:
  db: