version: "3.9"

services:
  atm_db:
    image: postgres
    container_name: my_atm_app
    restart: always
    environment:
      - POSTGRES_DB=atm_credit_db
      - POSTGRES_USER=alexey
      - POSTGRES_PASSWORD=alexey
    volumes:
      - db:/var/lib/postgresql/data postgres
#      - ./architect_module/src/main/resources/dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5460:5432"

volumes:
  db: