package com.example.architect_module.constants;

public class ArchitectConstants {

    public static final String BEGIN_OF_FILE_NAME = "architect_module/src/main/resources/db/migration/V00";
    public static final String TWO_UNDERLINES = "__";
    public static final String UNDERLINE = "_";
    public static final String END_OF_FILE_NAME = ".sql";
    public static final String EXECUTE_URL = "/execute";
    public static final String CREATE_COMMAND = "create";
    public static final String SELECT_VERSION = "select version from flyway_schema_history order by version desc limit 1";
    public static final String CREATE_TABLE = "create table if not exists ";
    public static final String ID_COLUMN = "id";
    public static final String PRIMARY_KEY = " BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,\n";
    public static final String CREATE_SEQUENCE = "create sequence ";
    public static final String SEQUENCE_SUFFIX = "_sequence;";
    public static final String SUCCESS_MESSAGE = "SUCCESS";

}
