package com.example.architect_module.constants;

public class ArchitectConstants {

    /**
     * Controller URL's
     */
    public static final String EXECUTE_URL = "/execute";
    public static final String BACKUP_URL = "/backup";

    /**
     * Base migration resources path
     */
    public static final String BASE_MIGRATION_RESOURCES_PATH = "architect_module/src/main/resources/db/migration";

    /**
     * Message constants
     */
    public static final String SUCCESS_EXECUTE_MESSAGE = "SUCCESS EXECUTE";
    public static final String SUCCESS_BACKUP_MESSAGE = "SUCCESS BACKUP";

    /**
     * Docker backup command
     */
    public static final String DOCKER_BACKUP_COMMAND = "docker exec -i my_atm_app /bin/bash -c \"PGPASSWORD=alexey pg_dump --username alexey atm_credit_db\" > architect_module/src/main/resources/dump/dump.sql";

    /**
     * Linux command
     */
    public static final String SH_COMMAND = "sh";
    public static final String SH_PARAM = "-c";

    /**
     * Creating SQL-scripts constants
     */
    public static final String BEGIN_OF_FILE_NAME = BASE_MIGRATION_RESOURCES_PATH + "/V00";
    public static final String TWO_UNDERLINES = "__";
    public static final String UNDERLINE = "_";
    public static final String END_OF_FILE_NAME = ".sql";
    public static final String OPEN_BRACKET_AND_NEW_LINE = " (\n";
    public static final String SPACE = " ";
    public static final String COMMA_AND_NEW_LINE = ",\n";
    public static final String CLOSE_BRACKET_AND_NEW_LINE = ");\n";

    /**
     * SQL constants
     */
    public static final String CREATE_COMMAND = "create";
    public static final String SELECT_VERSION_QUERY = "select version from flyway_schema_history order by version desc limit 1";
    public static final String CREATE_TABLE = "create table if not exists ";
    public static final String ID_COLUMN = "id";
    public static final String PRIMARY_KEY = " BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,\n";
    public static final String CREATE_SEQUENCE = "create sequence ";
    public static final String SEQUENCE_SUFFIX = "_sequence;";

}
