create table if not exists logs_user
(
    id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name              varchar,
    registration_date timestamp
);
create sequence logs_user_sequence;